# Generated by Django 4.2.6 on 2024-01-09 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0025_borrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrow',
            name='book_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='nickname',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.TextField(max_length=40),
        ),
    ]
